spring.application.name=authEv
server.port=8082

Eureka Client

eureka.client.service-url.defaultZone=https://eureka-server-pmc5.onrender.com/eureka
eureka.client.register-with-eureka=true
eureka.client.fetch-registry=true

eureka.instance.prefer-ip-address=true


usuario.service.url=${URL_usuarioservice:http://localhost:8081/api/v1/usuarios}